# Generated by Django 5.1.15 on 2026-07-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='assignment_weight',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=5),
        ),
        migrations.AddField(
            model_name='cohort',
            name='attendance_weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
